// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnBeforeClose(arg1) {
  return window['go']['app']['App']['OnBeforeClose'](arg1);
}

export function OnDomReady(arg1) {
  return window['go']['app']['App']['OnDomReady'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['App']['OnStartup'](arg1);
}
