// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;
